
services:
  postgres:
    image: postgres:16
    container_name: quizzcloud-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: quizzcloud
      POSTGRES_USER: quizzcloud_user
      POSTGRES_PASSWORD: quizzcloud_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: