name: SonarCloud + Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build with Maven and generate coverage
        run: mvn clean verify

      - name: Copy dependencies to target/dependency
        run: mvn dependency:copy-dependencies -DincludeScope=compile -DoutputDirectory=target/dependency

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v5
        with:
          args: >
            -Dsonar.projectKey=quizz-cloud-f5_quizz-cloud-back
            -Dsonar.organization=quizz-cloud-f5
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.java.binaries=target/classes
            -Dsonar.java.libraries=target/dependency
            -Dsonar.coverage.exclusions=src/test/**

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
