name: Docker Build & Publish

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract release version
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/quizzcloud-backend:${{ env.VERSION }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/quizzcloud-backend:${{ env.VERSION }}

      - name: Logout from GitHub Container Registry
        run: docker logout ghcr.io
